// Generated by CoffeeScript 1.6.3
(function () {
  var Vehicle;

  Vehicle = (function () {
    function Vehicle() {
      this.engine = new Engine();
      this.wheels = [];
    }

    return Vehicle;

  })();

  Vehicle.NUMBER_OF_WHEELS = 4;

}).call(this);

/*
//@ sourceMappingURL=example-coffee.map
*/
